source 'https://rubygems.org'

ruby '2.5.6'

gem 'rufus-scheduler'
gem 'tzinfo-data'
gem 'foreman'
gem 'mail'
gem 'httparty'
gem 'tilt'
gem 'haml'
gem 'redcarpet'
gem 'table_print'

group :development do
  gem 'pry'
  gem 'mailcatcher'
end

