# frozen_string_literal: true

ruby '2.4.2'
source 'https://rubygems.org'

gem 'dotenv'
gem 'octokit'
gem 'pry'
gem 'vcr'
gem 'webmock'
gem 'scraperwiki', git: 'https://github.com/openaustralia/scraperwiki-ruby.git', branch: 'morph_defaults'

group :development, :test do
  gem 'rubocop'
  gem 'rspec'
end
