source 'https://rubygems.org'

gem 'ruby-trello'
gem 'pry'
gem 'launchy'
gem 'slack-notifier'
gem 'rufus-scheduler'
gem 'scraperwiki', git: 'https://github.com/openaustralia/scraperwiki-ruby.git', branch: 'morph_defaults'
