# frozen_string_literal: true

ruby '2.6.3'
source 'https://rubygems.org'

gem 'bamboozled'
gem 'dotenv'
gem 'fuzzy_match'
gem 'rubytree'

group :development do
  gem 'pry'
  gem 'pry-byebug'
  gem 'rubocop'
end

group :test do
  gem 'rspec'
end
