name: check_nbn_appointments

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  check_and_notify:

    runs-on: ubuntu-latest
    env:
      working-directory: ./nbn

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - uses: actions/cache@v1
      with:
        path: nbn/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      working-directory: ${{env.working-directory}}
    - name: Run the appointment checker
      run: bundle exec ruby check_appointments.rb
      working-directory: ${{env.working-directory}}
