name: Save URLs to Wayback Machine
on:
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron:  '0 21,23 * * *' # UTC –> 7am, 9am AEST
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  save-urls:
    name: 💾 
    runs-on: ubuntu-latest
    steps:
    - name: "Save Redcliffe Magistrates Court Daily Law List"
      run: |
        wget https://web.archive.org/save/https://www.courts.qld.gov.au/__external/CourtsLawList/Redcliffe_DailyLawList.pdf
