name: Save URLs to Wayback Machine
on:
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron:  '0 21,23 * * *' # UTC –> 7am, 9am AEST
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  save-urls:
    runs-on: ubuntu-latest
    name: 💾
    strategy:
      fail-fast: false
      matrix:
        url:
          - https://www.courts.qld.gov.au/__external/CourtsLawList/Redcliffe_DailyLawList.pdf
          - https://www.vaultree.com/
          - https://www.vaultree.com/about-us/
          - https://www.vaultree.com/jobs/
          - https://www.strongsalt.com/
          - https://www.strongsalt.com/platform/
          - https://api.strongsalt.com/
          - https://www.verygoodsecurity.com/
          - https://www.verygoodsecurity.com/pricing
          - https://piiano.com/
          - https://piiano.com/product/
    steps:
    - name: "Save URL"
      run: |
        wget https://web.archive.org/save/${{ matrix.url }}
