name: Save URLs to Wayback Machine
on:
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron:  '0 21,23 * * *' # UTC –> 7am, 9am AEST
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  save-urls:
    runs-on: ubuntu-latest
    name: 💾
    strategy:
      fail-fast: false
      continue-on-error: true
      matrix:
        url:
          - https://www.courts.qld.gov.au/__external/CourtsLawList/Redcliffe_DailyLawList.pdf
    steps:
    - name: "Save URL"
      run: |
        wget https://web.archive.org/save/${{ matrix.url }}
